tailwind.config = {
    darkMode: "class",
    theme: {
      extend: {
        "colors": {
                "inverse-primary": "#76dd6f",
                "surface-variant": "#e5e2e1",
                "on-primary": "#ffffff",
                "primary-container": "#128220",
                "surface-container-highest": "#e5e2e1",
                "on-surface-variant": "#3f4a3c",
                "secondary-fixed": "#b0f2bf",
                "outline": "#6f7a6a",
                "surface-tint": "#006e15",
                "error-container": "#ffdad6",
                "on-tertiary-fixed": "#151d19",
                "inverse-on-surface": "#f3f0ef",
                "on-secondary-fixed": "#00210d",
                "on-secondary-container": "#337048",
                "on-primary-fixed": "#002202",
                "on-primary-container": "#dcffd2",
                "secondary-fixed-dim": "#95d5a4",
                "tertiary": "#515a54",
                "surface-dim": "#dcd9d9",
                "tertiary-fixed-dim": "#c0c9c1",
                "surface-container-lowest": "#ffffff",
                "surface": "#fcf9f8",
                "on-tertiary-container": "#eef7ef",
                "on-tertiary-fixed-variant": "#404943",
                "surface-container": "#f0eded",
                "on-background": "#1b1c1c",
                "inverse-surface": "#303030",
                "background": "#fcf9f8",
                "primary-fixed-dim": "#76dd6f",
                "on-primary-fixed-variant": "#00530d",
                "tertiary-container": "#69726c",
                "on-error-container": "#93000a",
                "on-error": "#ffffff",
                "outline-variant": "#becab8",
                "secondary-container": "#b0f2bf",
                "on-surface": "#1b1c1c",
                "on-secondary": "#ffffff",
                "secondary": "#2d6a42",
                "primary": "#006713",
                "surface-container-low": "#f6f3f2",
                "on-secondary-fixed-variant": "#10512c",
                "surface-container-high": "#eae7e7",
                "tertiary-fixed": "#dce5dd",
                "error": "#ba1a1a",
                "surface-bright": "#fcf9f8",
                "on-tertiary": "#ffffff",
                "primary-fixed": "#91fa88"
        },
        "borderRadius": {
                "DEFAULT": "0.5rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
        },
        "spacing": {
                "unit": "8px",
                "container-max": "1200px",
                "margin-mobile": "16px",
                "margin-desktop": "40px",
                "gutter": "24px"
        },
        "fontFamily": {
                "headline-xl": ["Manrope"],
                "body-md": ["Manrope"],
                "headline-md": ["Manrope"],
                "headline-lg": ["Manrope"],
                "label-sm": ["JetBrains Mono"],
                "headline-lg-mobile": ["Manrope"],
                "body-lg": ["Manrope"]
        },
        "fontSize": {
                "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
                "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
                "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
        }
      },
    },
  }